language: elixir
sudo: false

matrix:
  include:
    - otp_release: 19.3
      elixir: 1.4
    - otp_release: 20.1
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.1
      elixir: 1.5
