language: elixir
sudo: false
group: edge
elixir:
  - 1.9.4
otp_release:
  - 22.0
cache:
  directories:
    - _build
    - deps
env:
  - MIX_ENV=test
script:
  - mix coveralls.travis || travis_terminate 1
  - mix dialyzer --halt-exit-status || travis_terminate 1
  - mix format --dry-run --check-formatted
